name: Build and Release
on:
  workflow_dispatch:
  
env:
  FLUTTER_VERSION: '3.29.3'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Create keystore file
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Build APK
        run: flutter build apk --release

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          cd build/ios/iphoneos/
          mkdir Payload
          cp -r Runner.app Payload/
          zip -qq -r -9 app-release.ipa Payload

      - name: Upload iOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/app-release.ipa

  upload:
    runs-on: ubuntu-latest
    needs: [ build-android, build-ios ]
    permissions:
      contents: write 

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist/
          merge-multiple: true

      - name: Read version
        id: pubspec
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get Previous tag
        id: previoustag
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)
          echo "tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - name: Generate commit messages
        id: commits
        run: |
          # Get commits between the previous tag and the current HEAD
          COMMITS=$(git log ${{ steps.previoustag.outputs.tag }}..HEAD --pretty=format:"* %s (%h)")
          # Handle cases where there are no new commits
          if [ -z "$COMMITS" ]; then
            COMMITS="No changes since ${{ steps.previoustag.outputs.tag }}"
          fi
          # Use a delimiter for multiline output
          DELIMITER=$(uuidgen)
          echo "commits<<$DELIMITER" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "$DELIMITER" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.pubspec.outputs.version }}
          name: v${{ steps.pubspec.outputs.version }}
          body: |
            ## What's Changed
            ${{ steps.commits.outputs.commits }}

            **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.previoustag.outputs.tag }}...v${{ steps.pubspec.outputs.version }}
          files: |
            dist/flutter-apk/app-release.apk
            dist/bundle/release/app-release.aab
            dist/app-release.ipa
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}